version: "3.9"
services:
  cloud-config-server:
    image: kookooku/cloud-config-server:latest
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - CLOUD_SERVER_GIT_URI=https://github.com/songintae/spring-cloud-config-repository
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test
    depends_on:
      - rabbitmq

  cloud-config-client:
    image: kookooku/cloud-config-client:latest
    ports:
      - "8080"
    environment:
      - CLOUD_CONFIG_SERVER_HOST=cloud-config-server
      - CLOUD_CONFIG_SERVER_PORT=8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test
    depends_on:
      - rabbitmq
      - cloud-config-server

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test