version: "3.8"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test