version: "3.9"
services:
  cloud-config-server:
    image: kookooku/cloud-config-server:latest
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - CLOUD_SERVER_GIT_URI=${CLOUD_SERVER_GIT_URI}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq

  cloud-config-client:
    image: kookooku/cloud-config-client:latest
    ports:
      - "8080"
    environment:
      - CLOUD_CONFIG_SERVER_HOST=${CLOUD_CONFIG_SERVER_HOST}
      - CLOUD_CONFIG_SERVER_PORT=${CLOUD_CONFIG_SERVER_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
      - cloud-config-server

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}