server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songintae/spring-cloud-config-repository
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test