server:
  port: ${SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_SERVER_GIT_URI:https://github.com/songintae/spring-cloud-config-repository}
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:test}
    password: ${RABBITMQ_PASSWORD:test}